config/routes.rb
Rails.application.routes.draw do
  resources :services
  devise_for :users
  resources :clients
  resources :user_managements

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :service

    STATUS = [
        ["Active", "1"],
        ["Deactive", "2"]
      ]

      
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :clients
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_management.rb
class UserManagement < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        clients_path
      end
      
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :address, :policy_type, :company, :phone, :email, :policy_effective, :expiration_date, :premium, :status)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:service_name)
    end
end

app/controllers/user_managements_controller.rb
class UserManagementsController < ApplicationController
  before_action :set_user_management, only: %i[ show edit update destroy ]

  # GET /user_managements or /user_managements.json
  def index
    @user_managements = UserManagement.all
  end

  # GET /user_managements/1 or /user_managements/1.json
  def show
  end

  # GET /user_managements/new
  def new
    @user_management = UserManagement.new
  end

  # GET /user_managements/1/edit
  def edit
  end

  # POST /user_managements or /user_managements.json
  def create
    @user_management = UserManagement.new(user_management_params)

    respond_to do |format|
      if @user_management.save
        format.html { redirect_to user_management_url(@user_management), notice: "User management was successfully created." }
        format.json { render :show, status: :created, location: @user_management }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_managements/1 or /user_managements/1.json
  def update
    respond_to do |format|
      if @user_management.update(user_management_params)
        format.html { redirect_to user_management_url(@user_management), notice: "User management was successfully updated." }
        format.json { render :show, status: :ok, location: @user_management }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_managements/1 or /user_managements/1.json
  def destroy
    @user_management.destroy

    respond_to do |format|
      format.html { redirect_to user_managements_url, notice: "User management was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_management
      @user_management = UserManagement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_management_params
      params.require(:user_management).permit(:first_name, :last_name, :address, :policy_type, :company, :phone, :email, :policy_effective, :expiration_date, :premium, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/user_managements_helper.rb
module UserManagementsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="field col-sm-6">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, :required => true %>
    </div>

    <div class="field col-sm-6">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, :required => true %>
    </div>
  </div>

  <div class="row">       
  <div class="field col-sm-6">
    <%= form.label :address %>
    <%= form.text_area :address, :required => true %>
  </div>

  <div class="field col-sm-6">
    <%= form.label :policy_type %>
    <% form.number_field :policy_type %>
    <%= form.collection_select :policy_type, Service.order(:name),:id,:service_name, :prompt => "select one" %>  </div>
  </div>
<div class="row">
  <div class="field col-sm-6">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field col-sm-6">
    <%= form.label :phone %>
    <%= form.number_field :phone, :required => true %>
  </div>
  </div>
  <div class="row">

  <div class="field col-sm-6">
    <%= form.label :email %>
    <%= form.text_field :email, :required => true %>
  </div>

  <div class="field col-sm-6">
    <%= form.label :policy_effective %>
    <%= form.date_field :policy_effective, :required => true %>
  </div>
  </div>
<div class="row">
  <div class="field col-sm-6">
    <%= form.label :expiration_date %>
    <%= form.date_field :expiration_date %>
  </div>

  <div class="field col-sm-6">
    <%= form.label :premium %>
    <%= form.number_field :premium, :required => true %>
  </div>
  </div>
<div class="row">
  <div class="field col-sm-6">
    <%= form.label :status %>
   

    <%= form.select :status, Client::STATUS %>
  </div>

  <div class="actions mt-2  text-center">
    <%= form.submit 'Submit', :class => 'btn btn-success btn-lg' %>
  </div>
<% end %>
</div>

app/views/clients/edit.html.erb
<h1 class="text-center">Editing Client</h1>

<%= render 'form', client: @client %>


<%= link_to '<< Back', clients_path, class:" btn btn-secondary mt-5" %>

app/views/clients/index.html.erb
<%= link_to 'New Client', new_client_path, class: "btn btn-primary mt-2 float-right mb-2" %>

<h3 class="text-center">Clients</h3>

<table id="client">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Policy type</th>
      <th>Company</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Policy effective</th>
      <th>Expiration date</th>
      <th>Premium</th>
      <th>Status</th>
 
      <th ></th>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.address %></td>
        <td><%= Service.find(client.policy_type).service_name %></td>
        <td><%= client.company %></td>
        <td><%= client.phone %></td>
        <td><%= client.email %></td>
        <td><%= client.policy_effective %></td>
        <td><%= client.expiration_date %></td>
        <td><%= client.premium %></td>
        <td> <%= client.status ==1 ? "Active" : "Deactive" %></td>
       
        <td><%= link_to 'Update', edit_client_path(client), class: "btn btn-secondary btn-sm" %></td>
        <td><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script>
$(document).ready( function () {
    $('#client').DataTable({
      
    });
} );

</script>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to '<< Back', clients_path, class: "btn btn-secondary" %>

app/views/clients/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Policy type:</strong>
  <%= @client.policy_type %>
</p>

<p>
  <strong>Company:</strong>
  <%= @client.company %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Policy effective:</strong>
  <%= @client.policy_effective %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @client.expiration_date %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @client.premium %>
</p>

<p>
  <strong>Status:</strong>
  <%= @client.status ==1 ? "Active" : "Deactive" %>
</p>


<%= link_to '<< Back', clients_path, class:"btn btn-secondary mt-4" %>

app/views/layouts/_footer.html.erb
<br>
<br>
<br>

<footer>
  <div class="text-center">
     <footer> <small>&copy; Copyright <%= Time.current.year %></small> </footer> 
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header">

  <div class="wrapper active">

    <section>
      <header>
        <nav class="rad-navigation">
          <div class="rad-logo-container"><a class="rad-logo" href="/"> <img id="logo1" src="/images/test.png" alt="cdac-logo"><strong> User Management Portal</strong></a>
            <% if current_user.present? %>
            </div>
          <div class="rad-top-nav-container">
            <ul class="links">
              <li><%= "Welcome, #{current_user.email}" %></li>
              <li><%= link_to ' ', destroy_user_session_path, method: :delete, :class=>"fas fa-sign-out-alt" , :title=>"logout"%></li>
            </ul>
          </div>
        </nav>
      </header>
    </section>
    <% end %>
  	<div class="main_body">

  		<div class="sidebar_menu">
  	        <div class="inner__sidebar_menu">

  	        	<ul>
  		          <li>
  		            <a href="/clients" data-method="get">
  		              <span class="icon">
  		              	<i class="fas fa-tachometer-alt"></i></span>
  		              <span class="list">Dashboard</span>
  		            </a>
  		          </li>

					<li>
					<a href="/services" data-method="get">
					  <span class="icon"><i class="fas fa-gear"></i></span>
					  <span class="list">Services</span>
					</a>
				  </li>
				  <li>



  		          <li>
  		            <a href="/users/edit" data-method="get">
  		              <span class="icon"><i class="fas fa-address-book"></i></span>
  		              <span class="list">Profile</span>
  		            </a>
  		          </li>
  		          <li>

  		        </ul>

  		        <div class="hamburger">
  			        <div class="inner_hamburger">
  			            <span class="arrow">
  			                <i class="fas fa-long-arrow-alt-left"></i>
  			                <i class="fas fa-long-arrow-alt-right"></i>
  			            </span>
  			        </div>
  			    </div>

  	        </div>
  	    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "User Management Portal" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

<link href="https://nightly.datatables.net/css/jquery.dataTables.css" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
  
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
  
</head>

    <% if current_user && current_user.present? %>
    <body class="view-content">
      <%= render 'layouts/header' %>
      <main class="header">

            <div class="container">
            <br>
            <span class="notice text-center", id="notice"><%= notice %></span>
            <span class="alert text-center", id="alert"><%= alert %></span>
            <div class="content">
              <%= yield %>
            </div>
            <%= render 'layouts/footer' %>
          </div>
        </div>

      </div>

      </main>
    </body>
    <% else %>
    <body class="body">
      <div class="content">
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </body>
    <% end %>
    <script src="https://nightly.datatables.net/js/jquery.dataTables.js"></script>
</html>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :service_name %>
    <%= form.text_field :service_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<%= link_to 'New Service', new_service_path, class:"btn btn-primary float-right" %>

<h3 class="text-center">Services</h3>

<table>
  <thead>
    <tr>
      <th>Service name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.service_name %></td>
   
        <td><%= link_to 'Update', edit_service_path(service) %></td>
        <td><%= link_to 'Delete', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service name:</strong>
  <%= @service.service_name %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

app/views/user_managements/_form.html.erb
<%= form_with(model: user_management, local: true) do |form| %>
  <% if user_management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_management.errors.count, "error") %> prohibited this user_management from being saved:</h2>

      <ul>
        <% user_management.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :policy_type %>
    <%= form.number_field :policy_type %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :policy_effective %>
    <%= form.date_select :policy_effective %>
  </div>

  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.date_select :expiration_date %>
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.number_field :premium %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_managements/edit.html.erb
<h1>Editing User Management</h1>

<%= render 'form', user_management: @user_management %>

<%= link_to 'Show', @user_management %> |
<%= link_to 'Back', user_managements_path %>

app/views/user_managements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Managements</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Policy type</th>
      <th>Company</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Policy effective</th>
      <th>Expiration date</th>
      <th>Premium</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_managements.each do |user_management| %>
      <tr>
        <td><%= user_management.first_name %></td>
        <td><%= user_management.last_name %></td>
        <td><%= user_management.address %></td>
        <td><%= user_management.policy_type %></td>
        <td><%= user_management.company %></td>
        <td><%= user_management.phone %></td>
        <td><%= user_management.email %></td>
        <td><%= user_management.policy_effective %></td>
        <td><%= user_management.expiration_date %></td>
        <td><%= user_management.premium %></td>
        <td><%= user_management.status %></td>
        <td><%= link_to 'Show', user_management %></td>
        <td><%= link_to 'Edit', edit_user_management_path(user_management) %></td>
        <td><%= link_to 'Destroy', user_management, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Management', new_user_management_path %>

app/views/user_managements/new.html.erb
<h1>New User Management</h1>

<%= render 'form', user_management: @user_management %>

<%= link_to 'Back', user_managements_path %>

app/views/user_managements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user_management.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user_management.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user_management.address %>
</p>

<p>
  <strong>Policy type:</strong>
  <%= @user_management.policy_type %>
</p>

<p>
  <strong>Company:</strong>
  <%= @user_management.company %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user_management.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_management.email %>
</p>

<p>
  <strong>Policy effective:</strong>
  <%= @user_management.policy_effective %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @user_management.expiration_date %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @user_management.premium %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user_management.status %>
</p>

<%= link_to 'Edit', edit_user_management_path(@user_management) %> |
<%= link_to 'Back', user_managements_path %>